System.Net.WebException
  HResult=0x80131620
  Сообщение = An error occurred while sending the request.
  Источник = System.Net.Requests
  Трассировка стека:
   в System.Net.HttpWebRequest.GetResponse()
   в System.Net.WebClient.GetWebResponse(WebRequest request)
   в System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   в System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   в System.Net.WebClient.DownloadString(Uri address)
   в System.Net.WebClient.DownloadString(String address)
   в Program.<Main>$(String[] args) в C:\Users\vladi\source\repos\testtask\Program.cs:строка 4

  Изначально это исключение было создано в этом стеке вызовов: 
    [Внешний код]

Внутреннее исключение 1:
HttpRequestException: An error occurred while sending the request.

Внутреннее исключение 2:
IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..

Внутреннее исключение 3:
SocketException: An existing connection was forcibly closed by the remote host.